global:
  scrape_interval:     5s #
  evaluation_interval: 5s # 

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      # prometheus server address
      - targets: ['host.docker.internal:1200']

  - job_name: 'driver'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      # prometheus server address
      - targets: ['host.docker.internal:1201']
